name: Jira

on:
  workflow_call:

jobs:
  ticketValidation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: "Group-Expense-Manager/common-ci-cd"
          path: "common-ci-cd"
          ref: "main"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./common-ci-cd/.github/actions

      - name: Validate Jira ticket numbers
        run: node ./jira-ticket-validator.js "${{ github.event.pull_request.title }}"
