name: Jira

on:
  workflow_call:

jobs:
  ticketValidation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "Group-Expense-Manager/common-ci-cd"
          path: "common-ci-cd"
          ref: "main"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./common-ci-cd/.github/actions

      - name: Validate Jira ticket numbers
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == dependabot/* ]]; then
            echo "Dependabot PR detected. Skipping Jira ticket validation."
            exit 0
          fi
          node ./jira-ticket-validator.js "${{ github.event.pull_request.title }}"
        working-directory: ./common-ci-cd/.github/actions
